# Generated by Django 4.2 on 2023-04-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_en',
            field=models.CharField(max_length=499, null=True, verbose_name='nomi'),
        ),
        migrations.AddField(
            model_name='user',
            name='name_uz',
            field=models.CharField(max_length=499, null=True, verbose_name='nomi'),
        ),
        migrations.AddField(
            model_name='user',
            name='title_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='title_uz',
            field=models.TextField(null=True),
        ),
    ]
