# Generated by Django 4.2 on 2023-05-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_name_en_user_name_uz_user_title_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nomi')),
                ('subject', models.TextField()),
                ('number', models.PositiveIntegerField()),
                ('tg_name', models.CharField(max_length=200, verbose_name='telegram nomi')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
