# Generated by Django 4.2 on 2023-05-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_contack'),
    ]

    operations = [
        migrations.AddField(
            model_name='contack',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='nomi'),
        ),
        migrations.AddField(
            model_name='contack',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='nomi'),
        ),
        migrations.AddField(
            model_name='contack',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='nomi'),
        ),
        migrations.AddField(
            model_name='contack',
            name='number_en',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contack',
            name='number_ru',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contack',
            name='number_uz',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contack',
            name='subject_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contack',
            name='subject_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contack',
            name='subject_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contack',
            name='tg_name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='telegram nomi'),
        ),
        migrations.AddField(
            model_name='contack',
            name='tg_name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='telegram nomi'),
        ),
        migrations.AddField(
            model_name='contack',
            name='tg_name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='telegram nomi'),
        ),
        migrations.AddField(
            model_name='user',
            name='name_ru',
            field=models.CharField(max_length=499, null=True, verbose_name='nomi'),
        ),
        migrations.AddField(
            model_name='user',
            name='title_ru',
            field=models.TextField(null=True),
        ),
    ]
