# Generated by Django 4.2 on 2023-05-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_contack_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='number_en',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='number_ru',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='number_uz',
        ),
        migrations.AddField(
            model_name='user',
            name='url_name',
            field=models.URLField(default=2, max_length=400, verbose_name='Url name'),
            preserve_default=False,
        ),
    ]
